# NumPy: Fundamental Library for Scientific Computing

**Course:** Python Data Analysis
**Topic:** Introduction to NumPy

---

## What is NumPy?

NumPy is a fundamental library for scientific computing in Python. It provides:
- Support for arrays and matrices
- Collection of mathematical functions
- Fast vectorized operations

**Key Benefits:**
- Much faster than Python lists for mathematical operations
- Essential for machine learning and deep learning
- Foundation for pandas, matplotlib, and other data science libraries

## Installation

### Method 1: Using requirements.txt
```
pip install -r requirements.txt
```

### Method 2: Direct Installation
```
pip install numpy
```

In [6]:
# Import NumPy with alias 'np'
import numpy as np

print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.1


## Part 1: Creating Arrays

### 1D Arrays (One Dimensional)

In [7]:
# Create a 1D array from a Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print("Type:", type(arr1))
print("Shape:", arr1.shape)
print()

1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)



### 2D Arrays (Two Dimensional)

In [8]:
# Create a 2D array from nested lists
arr2 = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6]
])
print("2D Array:")
print(arr2)
print("Shape (rows, columns):", arr2.shape)
print("Total elements:", arr2.size)
print()

2D Array:
[[1 2 3 4 5]
 [2 3 4 5 6]]
Shape (rows, columns): (2, 5)
Total elements: 10



### Reshaping Arrays

Convert between different array dimensions

In [21]:
array2 = np.array([
  [1,2,3,4,5,6,7,8],
  [8,5,2,4,1,7,1,2]
])
print("Original Array : \n" ,array2)
arrshape = array2.reshape(16,1)
print("array shape " , arrshape.shape , arrshape)

Original Array : 
 [[1 2 3 4 5 6 7 8]
 [8 5 2 4 1 7 1 2]]
array shape  (16, 1) [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [8]
 [5]
 [2]
 [4]
 [1]
 [7]
 [1]
 [2]]


In [9]:
# Reshape 1D array to 2D
arr_1d = np.array([1, 2, 3, 4, 5])
arr_reshaped = arr_1d.reshape(1, 5)  # 1 row, 5 columns
print("Original (1D):", arr_1d)
print("Shape:", arr_1d.shape)
print()
print("Reshaped (2D):")
print(arr_reshaped)
print("Shape:", arr_reshaped.shape)
print()

# Reshape to 5 rows, 1 column
arr_reshaped2 = arr_1d.reshape(5, 1)
print("Reshaped (5x1):")
print(arr_reshaped2)
print()

Original (1D): [1 2 3 4 5]
Shape: (5,)

Reshaped (2D):
[[1 2 3 4 5]]
Shape: (1, 5)

Reshaped (5x1):
[[1]
 [2]
 [3]
 [4]
 [5]]



## Part 2: Creating Arrays with Built-in Functions

In [22]:
# Create arrays with specific values

# arange - creates array with values in a range with step
arr_arange = np.arange(0, 10, 2)  # 0 to 10, step by 2
print("np.arange(0, 10, 2):", arr_arange)
print()

# ones - create array filled with 1s
arr_ones = np.ones((3, 4))  # 3 rows, 4 columns
print("np.ones((3, 4)):")
print(arr_ones)
print()

# zeros - create array filled with 0s
arr_zeros = np.zeros((2, 3))
print("np.zeros((2, 3)):")
print(arr_zeros)
print()

# eye/identity - create identity matrix
arr_identity = np.eye(3)
print("np.eye(3) - Identity Matrix:")
print(arr_identity)
print()

np.arange(0, 10, 2): [0 2 4 6 8]

np.ones((3, 4)):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

np.zeros((2, 3)):
[[0. 0. 0.]
 [0. 0. 0.]]

np.eye(3) - Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## Part 3: Array Attributes

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:")
print(arr)
print()
print("--- Array Attributes ---")
print(f"shape: {arr.shape}")          # Dimensions (rows, columns)
print(f"ndim: {arr.ndim}")            # Number of dimensions
print(f"size: {arr.size}")            # Total number of elements
print(f"dtype: {arr.dtype}")          # Data type
print(f"itemsize: {arr.itemsize}")    # Size of each element in bytes
print()

Array:
[[1 2 3]
 [4 5 6]]

--- Array Attributes ---
shape: (2, 3)
ndim: 2
size: 6
dtype: int64
itemsize: 8



## Part 4: Vectorized Operations

Element-wise mathematical operations on arrays

In [24]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print("Array 1:", arr1)
print("Array 2:", arr2)
print()
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)
print("Power:", arr1 ** 2)
print()

Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Power: [ 1  4  9 16 25]



## Part 5: Universal Functions

Functions that apply element-wise operations to arrays

In [25]:
arr = np.array([1, 2, 3, 4, 5])

print("Original Array:", arr)
print()
print("--- Mathematical Functions ---")
print(f"np.sqrt(arr): {np.sqrt(arr)}")           # Square root
print(f"np.exp(arr): {np.exp(arr)}")            # Exponential
print(f"np.sin(arr): {np.sin(arr)}")            # Sine
print(f"np.log(arr): {np.log(arr)}")            # Natural logarithm
print(f"np.abs([-1, -2, 3]): {np.abs([-1, -2, 3])}")  # Absolute value
print()

Original Array: [1 2 3 4 5]

--- Mathematical Functions ---
np.sqrt(arr): [1.         1.41421356 1.73205081 2.         2.23606798]
np.exp(arr): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
np.sin(arr): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
np.log(arr): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
np.abs([-1, -2, 3]): [1 2 3]



## Part 6: Array Indexing and Slicing

Accessing specific elements or subsets of arrays

In [27]:
# Create a 2D array for demonstration
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original Array:")
print(arr)
print("Shape:", arr.shape)
print()

# Accessing single element
print("Element at [0, 0]:", arr[0, 0])
print("Element at [1, 2]:", arr[1, 2])
print()

# Accessing rows
print("First row:", arr[0])
print("Second row:", arr[1])
print()

# Slicing rows
print("Rows 0-1:")
print(arr[0:2])
print()

# Slicing columns
print("All rows, columns 0-2:")
print(arr[:, 0:2])
print()

# Slicing specific region
print("Rows 1-2, columns 1-3:")
print(arr[1:3, 1:3])
print()

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

Element at [0, 0]: 1
Element at [1, 2]: 7

First row: [1 2 3 4]
Second row: [5 6 7 8]

Rows 0-1:
[[1 2 3 4]
 [5 6 7 8]]

All rows, columns 0-2:
[[ 1  2]
 [ 5  6]
 [ 9 10]]

Rows 1-2, columns 1-3:
[[ 6  7]
 [10 11]]



In [42]:
arrr = np.array(
  [[1,2,3,4],
  [5,6,7,8],
  [9 ,10 ,11,12]]
)
print(f"array is \n {arrr}")

#need to print 6 7 10 11

print(f"\n print 6-7-10-11 : \n {arrr[1:,1:3]}")

array is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 print 6-7-10-11 : 
 [[ 6  7]
 [10 11]]


## Part 7: Modifying Array Elements

In [43]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original Array:")
print(arr)
print()

# Modify single element
arr[0, 0] = 100
print("After arr[0, 0] = 100:")
print(arr)
print()

# Modify entire row
arr[1, :] = 999
print("After arr[1, :] = 999:")
print(arr)
print()

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

After arr[0, 0] = 100:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

After arr[1, :] = 999:
[[100   2   3   4]
 [999 999 999 999]
 [  9  10  11  12]]



## Part 8: Statistical Operations

In [29]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Data:", data)
print()
print("--- Statistical Functions ---")
print(f"Mean: {np.mean(data)}")              # Average
print(f"Median: {np.median(data)}")          # Middle value
print(f"Standard Deviation: {np.std(data)}") # Spread of data
print(f"Variance: {np.var(data)}")           # Squared spread
print(f"Min: {np.min(data)}")                # Minimum value
print(f"Max: {np.max(data)}")                # Maximum value
print(f"Sum: {np.sum(data)}")                # Sum of all elements
print()

Data: [ 1  2  3  4  5  6  7  8  9 10]

--- Statistical Functions ---
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Sum: 55



## Part 9: Normalization (Practical Application)

Transform data to have mean = 0 and standard deviation = 1

In [30]:
# Original data
data = np.array([10, 20, 30, 40, 50])

print("Original Data:")
print(f"Values: {data}")
print(f"Mean: {np.mean(data):.2f}")
print(f"Std Dev: {np.std(data):.2f}")
print()

# Calculate mean and standard deviation
mu = np.mean(data)
sigma = np.std(data)

# Normalize: (X - mean) / std_dev
normalized_data = (data - mu) / sigma

print("Normalized Data:")
print(f"Values: {normalized_data}")
print(f"Mean: {np.mean(normalized_data):.10f}")  # Should be ~0
print(f"Std Dev: {np.std(normalized_data):.10f}") # Should be ~1
print()

Original Data:
Values: [10 20 30 40 50]
Mean: 30.00
Std Dev: 14.14

Normalized Data:
Values: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Mean: 0.0000000000
Std Dev: 1.0000000000



## Part 10: Logical Operations

Filtering arrays using conditions

In [31]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Data:", data)
print()

# Logical condition - returns boolean array
print("data > 5:")
print(data > 5)
print()

# Filter elements greater than 5
filtered = data[data > 5]
print("Elements > 5:", filtered)
print()

# Multiple conditions
print("Elements >= 5 AND <= 8:")
filtered2 = data[(data >= 5) & (data <= 8)]
print(filtered2)
print()

# OR condition
print("Elements < 3 OR > 8:")
filtered3 = data[(data < 3) | (data > 8)]
print(filtered3)
print()

Data: [ 1  2  3  4  5  6  7  8  9 10]

data > 5:
[False False False False False  True  True  True  True  True]

Elements > 5: [ 6  7  8  9 10]

Elements >= 5 AND <= 8:
[5 6 7 8]

Elements < 3 OR > 8:
[ 1  2  9 10]



## Summary

**Key Takeaways:**
1. NumPy provides efficient arrays for numerical computing
2. Arrays can be created from lists or using built-in functions
3. Vectorized operations are much faster than loops
4. Universal functions apply operations element-wise
5. Indexing and slicing allow easy access to array elements
6. Statistical functions help analyze data
7. Logical operations enable filtering and conditional selection

**Next Topics:**
- Pandas: Building on NumPy for data analysis
- Matplotlib: Data visualization
- Machine Learning: Using NumPy for algorithms